# Site settings
title: Jennifer Hiller
description: Personal Website
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jennifer Hiller
user_description: A software engineer with a specialty in HTML, CSS, and JavaScript.
user_title: Web Programmer | Musician | Artist
email: jenn@jennhiller.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
