name: Deploy to Cloudflare Pages hosting

on:
  push:
    branches:
      - dev
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: npm install && npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 59ab0f165887221cd7839052a1b1f764
          projectName: jennhiller
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
